STRING = 'string(16777216)'
TIMESTAMP = 'timestamp'
DECIMAL = 'decimal(38,6)'
BIGINT = 'bigint'
ARRAY_STRING = 'array<string>'
MAP_STRING_STRING = 'map<string,string>'
BOOLEAN = 'boolean'
VARIANT = 'variant'